<a href="https://colab.research.google.com/github/arminshabanian/Text-Preprocessing-and-Clustering-with-Weighed-Inverted-Indexing/blob/main/text_clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP PROJECT
---
##SOURCE
###A zip file which consists of 1401 XML files which the teacher sent and is uploaded to Google Drive

---
##DATA DESCRIPTION
###DOC TAG
> Contain some tags

###DOCNO TAG
> This tag shows the number of the article in dataset
###TITLE TAG
> Shows us the title of article
###AUTHOR TAG
> The name of the author
###BIBLIO TAG
> Biblio
###TEXT TAG
> Contain a text




##PREPROCESSING

###STEP_1 : Load the data (located in the data folder)





####CLEAR DIRECTORY

In [ ]:
!rm -r *

rm: cannot remove '*': No such file or directory


#### Read Data From Google Drive

In [ ]:
!gdown 1XUA-YxiOTOog0uHNGeyRzEFX6vBaNaZQ

Downloading...
From: https://drive.google.com/uc?id=1XUA-YxiOTOog0uHNGeyRzEFX6vBaNaZQ
To: /content/Data.zip
100% 1.05M/1.05M [00:00<00:00, 100MB/s]


####Unzip And Prepare Data







In [ ]:
!unzip -q Data.zip
!rm ./Data/Untitled.m

###STEP_2 : Perform tokenization

####FUNCTION FOR READ DATA WITH THEIR NAME

In [ ]:
import xml.etree.ElementTree as ET
def header(filename):
    tree = ET.parse(filename) #read in the XML
    for dc in tree.iter(tag = 'DOC'):
      name = dc.find('TEXT').text
      return name.split()


####CREATE LIST OF FILES NAME

In [ ]:
import os

# folder path
dir_path = r'Data'

# list to store files
res = []

# Iterate directory
for path in os.listdir(dir_path):
    # check if current path is a file
    if os.path.isfile(os.path.join(dir_path, path)):
        res.append(path)
res.sort()
print(res)

['cranfield0001', 'cranfield0002', 'cranfield0003', 'cranfield0004', 'cranfield0005', 'cranfield0006', 'cranfield0007', 'cranfield0008', 'cranfield0009', 'cranfield0010', 'cranfield0011', 'cranfield0012', 'cranfield0013', 'cranfield0014', 'cranfield0015', 'cranfield0016', 'cranfield0017', 'cranfield0018', 'cranfield0019', 'cranfield0020', 'cranfield0021', 'cranfield0022', 'cranfield0023', 'cranfield0024', 'cranfield0025', 'cranfield0026', 'cranfield0027', 'cranfield0028', 'cranfield0029', 'cranfield0030', 'cranfield0031', 'cranfield0032', 'cranfield0033', 'cranfield0034', 'cranfield0035', 'cranfield0036', 'cranfield0037', 'cranfield0038', 'cranfield0039', 'cranfield0040', 'cranfield0041', 'cranfield0042', 'cranfield0043', 'cranfield0044', 'cranfield0045', 'cranfield0046', 'cranfield0047', 'cranfield0048', 'cranfield0049', 'cranfield0050', 'cranfield0051', 'cranfield0052', 'cranfield0053', 'cranfield0054', 'cranfield0055', 'cranfield0056', 'cranfield0057', 'cranfield0058', 'cranfield005

####CREATE LIST OF OUT FILES

In [ ]:
all_text_list=[]
for r in res :
  all_text_list.append(header('./Data/'+r))

###STEP_3 : Delete stop words

#### Download stop words from a library and put it into a list

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


####Print stop words

In [ ]:
for i in range(0,len(stop_words),20):
  print(*stop_words[i:i+20],sep=" ")
  print('\n')


i me my myself we our ours ourselves you you're you've you'll you'd your yours yourself yourselves he him his


himself she she's her hers herself it it's its itself they them their theirs themselves what which who whom this


that that'll these those am is are was were be been being have has had having do does did doing


a an the and but if or because as until while of at by for with about against between into


through during before after above below to from up down in out on off over under again further then once


here there when where why how all any both each few more most other some such no nor not only


own same so than too very s t can will just don don't should should've now d ll m o


re ve y ain aren aren't couldn couldn't didn didn't doesn doesn't hadn hadn't hasn hasn't haven haven't isn isn't


ma mightn mightn't mustn mustn't needn needn't shan shan't shouldn shouldn't wasn wasn't weren weren't won won't wouldn wouldn't




#### Delete stop words from text list

In [ ]:
filtered_list=[]
for i in all_text_list:
  filtered_list.append([w for w in i if not w.lower() in stop_words])

####Compare length of first item in filtered_list with all_text_list (index 0)

In [ ]:
print(len(all_text_list[0]),len(filtered_list[0]))

131 77


###STEP_4 : According to the data, remove any extra characters (for example: tags, punctuation, etc.) in the data and clean the data.


#### one example of punctuation in our text

In [ ]:
print(filtered_list[0][50])

/destalling/


#### replace punctuation with blank character



In [ ]:
All_punct = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
# we can use re library too

for i in range(len(filtered_list)):
  for j in range(len(filtered_list[i])):
    for k in filtered_list[i][j]:
      if k in All_punct:
        filtered_list[i][j] = filtered_list[i][j].replace(k, "")
        # replace them with blank character
        # some items equal to '' so we should delete them

print(filtered_list[0][50])

destalling


#### delete blank string from list

In [ ]:
for i in range(len(filtered_list)):
  filtered_list[i] = [j for j in filtered_list[i] if j not in '']

###STEP_5 : Perform stemming

In [ ]:
# import these modules
from nltk.stem import PorterStemmer

ps = PorterStemmer()

for i in range(len(filtered_list)):
  filtered_list[i]=[ps.stem(j) for j in filtered_list[i]]

# print some items of list
for w in filtered_list[0][:10]:
    print(w,sep=' \t')

experiment
studi
wing
propel
slipstream
made
order
determin
spanwis
distribut


##INDEXING

###STEP_1 : After collecting all the tokens, Build an inverted index

#### Append all words into an array

In [ ]:
all_words=[]

for i in range(len(filtered_list)):
  k = [j for j in filtered_list[i]]
  all_words+=k

print('All Words : ',len(all_words))

all_words_set=set(all_words)
# remove repetitious values
print('All Words Whitout Repetitious : ',len(all_words_set))
all_words_set=list(all_words_set)

All Words :  116754
All Words Whitout Repetitious :  6310


####Create inverted index

In [ ]:
import numpy as np

inverted_index=np.zeros((len(filtered_list),6310), dtype=int)

for i in range(len(filtered_list)):
  for j in range(len(filtered_list[i])):
    k=filtered_list[i][j]
    if k in all_words_set:
      h= all_words_set.index(k)
      inverted_index[i,h]+=1



####Some examples of array

In [ ]:
print('some index with value of 1 : ',end='')
for i in range(500):
  if(inverted_index[0,i]==1):
    print(i,end=' ')
print()
print('value of index 164 : ',all_words_set[164])
print('is \'togeth\' in my list : ',filtered_list[0].count('togeth'))

some index with value of 1 : 62 242 249 
value of index 164 :  hotwir
is 'togeth' in my list :  1


##CLUSTERING

###STEP_1 : Load the weighted data from previous HW

####calculate tf/idf

In [ ]:
# import math

# # this function calculates the term frequency
# def calculate_tf(term, document):
#   return term / len(document)

# # this function calculates the inverse document frequency
# def calculate_idf(term, documents):
#     num_documents_with_term = sum(1 for doc in documents if term in doc)
#     return math.log(len(documents) / (num_documents_with_term + 1)) + 1

# # this function calculates the tf/idf
# def calculate_tfidf(term, document, documents):
#     tf = calculate_tf(term, document)
#     idf = calculate_idf(term, documents)
#     if tf * idf != 0 :
#       print (tf * idf)
#     return tf * idf

# # Create a zeros array with the same shape as arr
# weighted_inverted_index = np.zeros_like(inverted_index,  dtype=np.float32)

# for i in range(len(inverted_index)):
#   print(i)
#   for j in range(len(inverted_index[i])):
#     if inverted_index[i, j] != 0 :
#       weighted_inverted_index[i, j] = calculate_tfidf(inverted_index[i, j], inverted_index[i], inverted_index)

####make txt file and convert it to zip

In [ ]:

# # Specify the file path
# folder_path = "/content/"  # Update with your desired folder path
# file_name = "weighted_inverted_index.txt"

# # Create the file path
# file_path = folder_path + file_name

# # Save the array to a text file
# np.savetxt(file_path, weighted_inverted_index, fmt='%.8f')

# print("File saved successfully.")

In [ ]:
# import zipfile

# # Path to the file you want to zip
# file_path = "/content/weighted_inverted_index.txt"

# # Name of the output zip file
# output_zip = "/content/weighted_inverted_index.zip"

# # Create a ZipFile object and open the zip file in write mode
# with zipfile.ZipFile(output_zip, "w") as zipf:
#     # Add the file to the zip
#     zipf.write(file_path, arcname="sample_file.txt")

# # Verify the zip file is created
# if os.path.exists(output_zip):
#     print("Zip file created successfully!")
# else:
#     print("Failed to create the zip file.")

####download zip file from google drive then unzip

In [ ]:
!gdown 1bsoF96R7cQqwZs1mrV9W4VfniJNrDo7i

Downloading...
From: https://drive.google.com/uc?id=1bsoF96R7cQqwZs1mrV9W4VfniJNrDo7i
To: /content/weighted_inverted_index.zip
100% 421k/421k [00:00<00:00, 140MB/s]


In [ ]:
import zipfile

# Specify the path to the zip file
zip_file_path = '/content/weighted_inverted_index.zip'

# Specify the destination folder to extract the files
destination_folder = '/content/'

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(destination_folder)

print('File extracted successfully.')


File extracted successfully.


####convert txt file into Numpy array

In [ ]:
# Specify the path to the text file
text_file_path = '/content/weighted_inverted_index.txt'

# Load the text file into a NumPy array
weighted_inverted_index = np.loadtxt(text_file_path, dtype=float)

# Print the array
print('one example of my data ==> data[0][37] : ', weighted_inverted_index[0,37])


one example of my data ==> data[0][37] :  0.00015837


In [ ]:
weighted_inverted_index.shape

(1400, 6310)

###STEP_2 : Perform k means clustering on them

In [ ]:
# import numpy as np

# def k_means_clustering(data, k, max_iterations=100):
#     # Initialize k centroids
#     centroids = data[np.random.choice(range(len(data)), k, replace=False)]

#     for _ in range(max_iterations):
#         labels = assign_labels(data, centroids)
#         new_centroids = update_centroids(data, labels, k)

#         if np.all(centroids == new_centroids):
#             break

#         centroids = new_centroids

#     return labels, centroids

# def assign_labels(data, centroids):
#     labels = []

#     for point in data:
#         distances = [distance(point, centroid) for centroid in centroids]
#         # np.argmin returns the index of min value
#         label = np.argmin(distances)
#         labels.append(label)

#     return np.array(labels)

# def distance(point, centroid):
#     # Calculate the distance using a different norm 2
#     return np.linalg.norm(point - centroid, ord=2)

#     # squared_sum = 0
#     # for i in range(len(point)):
#     #     squared_sum += (point[i] - centroid[i]) ** 2
#     # # Taking the square root to get the Euclidean distance
#     # return squared_sum ** 0.5

# def update_centroids(data, labels, k):
#     centroids = []

#     for i in range(k):
#         cluster_points = data[labels == i]
#         centroid = np.mean(cluster_points, axis=0)
#         centroids.append(centroid)

#     return np.array(centroids)



In [ ]:
# data = weighted_inverted_index.copy()

# # Perform k-means clustering
# labels, centroids = k_means_clustering(data, k=200)

# # Print the results
# print("Cluster Labels:", labels)
# print("Cluster Centers:", centroids)


##Try with different norm

###STEP_1 : Perform k means clustering with norm0, norm1

####norm_1

In [ ]:
import numpy as np

def k_means_clustering_norm_1(data, k, max_iterations=100):
    # Initialize k centroids
    centroids = data[np.random.choice(range(len(data)), k, replace=False)]

    for _ in range(max_iterations):
        labels = assign_labels(data, centroids)
        new_centroids = update_centroids_median(data, labels, k)

        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return labels, centroids


def assign_labels(data, centroids):
    labels = []

    for point in data:
        distances = [distance(point, centroid) for centroid in centroids]
        label = np.argmin(distances)
        labels.append(label)

    return np.array(labels)


def distance(point, centroid):
    return np.linalg.norm(point - centroid, ord=1)


def update_centroids_median(data, labels, k):
    centroids = []

    for i in range(k):
        cluster_points = data[labels == i]
        centroid = np.median(cluster_points, axis=0)
        centroids.append(centroid)

    return np.array(centroids)



In [ ]:
data_norm_1 = weighted_inverted_index.copy()

# Perform k-means clustering
labels_norm_1, centroids_norm_1 = k_means_clustering_norm_1(data_norm_1, k=200)

# Print the results
print("Cluster Labels norm_1:", labels_norm_1)
print("Cluster Centers norm_1:", centroids_norm_1)
# print("Cluster Centers norm_1:", centroids)

Cluster Labels norm_1: [123 123 123 ...  46 123 123]
Cluster Centers norm_1: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
np.isnan(data_norm_1).any()

False

####norm_0

In [ ]:
from scipy.stats import mode

def k_means_clustering_norm_0(data, k, max_iterations=100):
    # Initialize k centroids
    centroids = data[np.random.choice(range(len(data)), k, replace=False)]

    for _ in range(max_iterations):
        labels = assign_labels(data, centroids)
        new_centroids = update_centroids_mode(data, labels, k)

        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids

    return labels, centroids


def assign_labels(data, centroids):
    labels = []

    for point in data:
        distances = [distance(point, centroid) for centroid in centroids]
        label = np.argmin(distances)
        labels.append(label)

    return np.array(labels)


def distance(point, centroid):
    return np.count_nonzero(point - centroid)


def update_centroids_mode(data, labels, k):
    centroids = []

    for i in range(k):
        cluster_points = data[labels == i]
        centroid = mode(cluster_points, axis=0).mode[0]
        centroids.append(centroid)

    return np.array(centroids)


In [ ]:
data_norm_0 = weighted_inverted_index.copy()

# Perform k-means clustering
labels_norm_0, centroids_norm_0 = k_means_clustering_norm_0(data_norm_0, k=200)

# Print the results
print("Cluster Labels norm_0 :", labels_norm_0)
print("Cluster Centers norm_0 :", centroids_norm_0)
# print("Cluster Centers:", centroids)

<ipython-input-30-aae3f298e859>:93: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  centroid = mode(cluster_points, axis=0).mode[0]


Cluster Labels norm_0 : [ 36 114  36 ...  36 161  36]
Cluster Centers norm_0 : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
